// Source/Admin/Web.React/src/app/components/healthrisks/HealthRiskList.js
import React from 'react';
import { AllHealthRisks, DeleteHealthRisk, HealthRisk } from '../../../dolittle.imports'; 
import { CommandCoordinator } from '@dolittle/commands';
import { QueryCoordinator } from '@dolittle/queries';

export class HealthRiskList extends React.Component{
    constructor(props) {
        super(props);
        
        /*this.queryCoordinator.execute(new AllHealthRisks())
            .then(response => {
                if (response.success) {
                    this.risks = response.items;
                    this.sortRisks('id')
                } else {
                    console.error(response);
                }
            })
            .catch(response => {
                console.error(response);
            });*/
    }
    
    render() {
        return (
          <div>This is the health risk component.</div>
        );
    }
}

// Source/Admin/Web/src/app/HealthRisks/healthRisk-list/healthRisk-list.component.ts
import { Component, OnInit, TemplateRef } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { HealthRisk } from '../HealthRisk';
import { DeleteHealthRisk } from '../DeleteHealthRisk';
import { AllHealthRisks } from '../AllHealthRisks';
import { CommandCoordinator } from '@dolittle/commands';
import { QueryCoordinator } from '@dolittle/queries';

@Component({
    selector: 'cbs-healthRisk-list',
    templateUrl: './healthRisk-list.component.html',
    styleUrls: ['./healthRisk-list.component.scss']
})

export class HealthRiskListComponent implements OnInit {
    risks: HealthRisk[];
    sortType: string;
    sortReverse: boolean = false;


    deleteHealthRiskCmd: DeleteHealthRisk = new DeleteHealthRisk();
    constructor(
        private queryCoordinator: QueryCoordinator,
        private commandCoordinator: CommandCoordinator,
        private toastr: ToastrService
    ) { }

    ngOnInit() {
        this.queryCoordinator.execute(new AllHealthRisks())
            .then(response => {
                if (response.success) {
                    this.risks = response.items as HealthRisk[];
                    this.sortRisks('id')
                } else {
                    console.error(response);
                }
            })
            .catch(response => {
                console.error(response);
            });
    }

    sortRisks(property) {
        this.sortType = property;
        this.sortReverse = !this.sortReverse;
        this.risks.sort(this.dynamicSort(property));
    }

    dynamicSort(property) {
        let sortRisk = -1;
        if (this.sortReverse)
            sortRisk = 1;
        return function (a, b) {
            let result = (a[property] < b[property]) ? -1 : (a[property] > b[property]) ? 1 : 0;

            return result * sortRisk;
        }
    }

}

<h3>
        Health Risks
</h3>

<a routerLink="add">
    <button type="button" class="btn btn-primary pull-right">Add Health Risk</button>
</a>

<table class="table table-bordered table-striped">
    
    <thead>
        <tr>
            <th (click)="sortRisks('healthRiskNumber')"> ID
                <span [ngClass]="!sortReverse?'fa fa-caret-down':'fa fa-caret-up'"></span>
            </th>
            <th>Health risk</th>
            <th>Case Definition</th>
            <th>Key Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let risk of risks">
            <td>{{ risk.healthRiskNumber }}</td>
            <td>{{ risk.name }}</td>
            <td>{{ risk.caseDefinition }}</td>
            <td>
                <a [routerLink]="[risk.id,'update']" routerLinkActive="active">Edit</a> | <cbs-delete-healthrisk [risk]=risk></cbs-delete-healthrisk>
            </td>
        </tr>
    </tbody>
</table>
